callback:
  eval_exploration_callback:
    class_path: src.callbacks.Plan2ExploreEvalCallback
    init_args:
      log_path: p2e-eval
      eval_freq: 20
  exploration_callback:
    class_path: src.callbacks.ExplorationCallback
    init_args:
      steps_per_rollout: 512
      rollout_grad_steps: 16384
exploration:
  algorithm: src.plan2explore.plan2explore.Plan2Explore
  policy: src.plan2explore.policies.CEMRLExplorationPolicy
  replay_buffer: src.cemrl.buffers.CEMRLReplayBuffer
main:
  policy:
    init_args:
      config:
        task_inference:
          decoder:
            ensemble_size: 5