policy_algorithm: src.cemrl.cemrl.CEMRLSACPolicy
replay_buffer: src.cemrl.buffers.EpisodicBuffer
policy:
  class_path: src.cemrl.policies.CEMRLPolicy
callback:
  callbacks:
    class_path: stable_baselines3.common.callbacks.CallbackList
    init_args:
      callbacks:
        - stable_baselines3.common.callbacks.ProgressBarCallback
        - class_path: src.callbacks.CheckpointInLogFolderCallback
          init_args:
            save_freq: 100
            save_path: checkpoints
  eval_callback:
    class_path: src.callbacks.EvalInLogFolderCallback
    init_args:
      log_path: eval
      eval_freq: 100
      n_eval_episodes: 32
      callback_on_new_best:
        class_path: src.callbacks.RecordVideo
        init_args:
          save_path: eval
  eval_exploration_callback:
    class_path: src.callbacks.Plan2ExploreEvalCallback
    init_args:
      log_path: p2e-eval
      eval_freq: 100
      n_eval_episodes: 32
      callback_on_new_best:
        class_path: src.callbacks.RecordVideo
        init_args:
          save_path: p2e-eval
  exploration_callback:
    class_path: src.callbacks.ExplorationCallback
    init_args:
      exploration_algorithm:
        class_path: src.plan2explore.plan2explore.Plan2Explore
        init_args:
          policy: src.plan2explore.policies.CEMRLExplorationPolicy
learn:
  tb_log_name: default
  log_interval: 1