main:
  policy:
    init_args:
      config:
        task_inference:
          encoder:
            latent_dim: 1
            complexity: 20.0
            preprocessed_state_size: 1
          decoder:
            complexity: 20.0
            ensemble_size: 3
        training:
          num_decoder_targets: 400
  replay_buffer:
    init_args:
      bin_weighted_sampling_mode: "reward"