env:
  init_args:
    venv:
      init_args:
        venv:
          init_args:
              venv:
                init_args:
                  random_position: True
tensorboard_log: "logs/toy-goal-1d/p2e-cemrl/random_start"