main:
  algorithm:
    init_args:
      tensorboard_log: "logs/toy-goal-2d/cemrl/stationary"
envs:
  env:
    non_stationary:
      init_args:
        change_after_timestep: 9999999
  eval_env:
    non_stationary:
      init_args:
        change_after_timestep: 9999999
  exploration_env: ${envs.env}
  exploration_eval_env: ${envs.eval_env}