main:
  algorithm: thesis.cemrl.algorithm.Cemrl
  replay_buffer: thesis.core.buffer.ReplayBuffer
  policy: thesis.cemrl.policy.CemrlPolicy
sub_algorithm: 
  algorithm: null
  policy: null
exploration:
  algorithm: null
  policy: null