main:
  algorithm: src.cemrl.cemrl.CEMRL
  replay_buffer: src.cemrl.buffers.EpisodeLinkingCemrlReplayBuffer
  policy: src.cemrl.policies.CEMRLPolicy
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-3
sub_algorithm: 
  algorithm: 
    class_path: stable_baselines3.sac.SAC
    init_args:
      learning_rate: 1e-3
  policy: stable_baselines3.sac.policies.MultiInputPolicy
exploration:
  algorithm: null
  policy: null
learn:
  tb_log_name: cemrl