main:
  algorithm: src.cemrl.cemrl.CEMRL
  replay_buffer: src.cemrl.buffers.CEMRLReplayBuffer
  policy: src.cemrl.policies.CEMRLPolicy
sub_algorithm: 
  algorithm: 
    class_path: stable_baselines3.sac.SAC
    init_args:
      learning_rate: 1e-3
  policy: stable_baselines3.sac.policies.MultiInputPolicy
exploration:
  algorithm: null
  policy: null
exploration_sub_algorithm:
  algorithm: null
  policy: null