callback:
  eval_exploration_callback:
    class_path: src.callbacks.P2EEvalCallback
    init_args:
      log_path: p2e-eval
      eval_freq: 20
  exploration_callback:
    class_path: src.callbacks.ExplorationCallback
    init_args:
      steps_per_rollout: 20
      pre_train_steps: 200_000
      train_on_rollout: true
exploration:
  algorithm: src.p2e.p2e.P2E
  policy: src.p2e.policies.P2EPolicy
learn:
  tb_log_name: cemrl-p2e
