callback:
  eval_exploration_callback:
    class_path: src.callbacks.Plan2ExploreEvalCallback
    init_args:
      log_path: p2e-eval
      eval_freq: 20
  exploration_callback:
    class_path: src.callbacks.ExplorationCallback
    init_args:
      steps_per_rollout: 512
      pre_train_steps: 1024000
      train_on_rollout: false
exploration:
  algorithm: src.p2e.algorithm.P2E
  policy: src.p2e.policies.P2EPolicy
exploration_sub_algorithm:
  algorithm: 
    class_path: stable_baselines3.sac.SAC
    init_args:
      learning_rate: 1e-3
  policy: stable_baselines3.sac.policies.MultiInputPolicy