envs:
  env:
    n_envs: 64
    time_limit: 200
    vec_env: stable_baselines3.common.vec_env.DummyVecEnv
    cemrl_wrapper: src.cemrl.wrappers.CEMRLWrapper
    heatmap: src.envs.wrappers.heatmap.HeatmapWrapper
    success: src.envs.wrappers.success.PercentageSuccessWrapper
    non_stationary:
      class_path: src.envs.wrappers.non_stationary.NonStationaryWrapper
      init_args:
        change_after_timestep: 100
    env:
      class_path: src.envs.toy_goal_env.ToyGoalEnv
      init_args:
        goal_sampler: src.envs.samplers.random_box_sampler.RandomBoxSampler
  eval_env:
    n_envs: 36
    time_limit: 300
    vec_env: stable_baselines3.common.vec_env.DummyVecEnv
    cemrl_wrapper: ${envs.env.cemrl_wrapper}
    heatmap: ${envs.env.heatmap}
    success: ${envs.env.success}
    non_stationary:
      class_path: src.envs.wrappers.non_stationary.NonStationaryWrapper
      init_args:
        change_after_timestep: 150
    env:
      class_path: src.envs.toy_goal_env.ToyGoalEnv
      init_args:
        goal_sampler: src.envs.samplers.UniformCircleSampler
  exploration_env: ${envs.env}
  exploration_eval_env: ${envs.eval_env}
learn:
  total_timesteps: 1_000_000
