policy_algorithm: src.cemrl.cemrl.CEMRLSACPolicy
policy:
  class_path: src.cemrl.policies.CEMRLPolicy
  init_args:
    latent_dim: 2
env:
  class_path: src.cemrl.wrappers.CEMRLHistoryWrapper
  init_args:
    venv:
      class_path: src.env.wrappers.heatmap.HeatmapWrapper
      init_args:
        venv:
          class_path: src.env.toy_goal_env.ToyGoalEnv
          init_args:
            num_envs: 256
            goal_sampler: src.env.samplers.random_box_sampler.RandomBoxSampler
replay_buffer: src.cemrl.buffers.CEMRLBuffer
gradient_steps: 2
encoder_window: 30
tensorboard_log: "logs/p2e-cemrl"
learn:
  total_timesteps: 1_000_000
  log_interval: 1
callback:
  callbacks:
    class_path: stable_baselines3.common.callbacks.CallbackList
    init_args:
      callbacks:
        - stable_baselines3.common.callbacks.ProgressBarCallback
        - class_path: src.callbacks.CheckpointInLogFolderCallback
          init_args:
            save_freq: 100
            save_path: checkpoints
  eval_callback:
    class_path: src.callbacks.EvalInLogFolderCallback
    init_args:
      log_path: eval
      eval_env:
        class_path: src.cemrl.wrappers.CEMRLHistoryWrapper
        init_args:
          venv:
            class_path: src.env.wrappers.heatmap.HeatmapWrapper
            init_args:
              venv:
                class_path: src.env.toy_goal_env.ToyGoalEnv
                init_args:
                  num_envs: 16
                  goal_sampler: src.env.samplers.UniformCircleSampler
          n_stack: ${encoder_window}
      eval_freq: 100
      callback_on_new_best:
        class_path: src.callbacks.RecordVideo
        init_args:
          save_path: eval
      render: true
  eval_exploration_callback:
    class_path: src.callbacks.Plan2ExploreEvalCallback
    init_args:
      log_path: p2e-eval
      eval_freq: 100
      callback_on_new_best:
        class_path: src.callbacks.RecordVideo
        init_args:
          save_path: p2e-eval
      render: true
  save_heatmap_callback:
    class_path: src.callbacks.SaveHeatmapCallback
    init_args:
      save_freq: 100
  exploration_callback:
    class_path: src.callbacks.ExplorationCallback
    init_args:
      exploration_algorithm:
        class_path: src.plan2explore.plan2explore.Plan2Explore
        init_args:
          policy: src.plan2explore.policies.CEMRLExplorationPolicy
