envs:
  env:
    n_envs: 512
    time_limit: 200
    vec_env: stable_baselines3.common.vec_env.DummyVecEnv
    cemrl_wrapper:
        class_path: src.cemrl.wrappers.CEMRLWrapper
        init_args:
          n_stack: 30
    heatmap: src.envs.wrappers.heatmap.HeatmapWrapper
    success: src.envs.wrappers.success.PercentageSuccessWrapper
    non_stationary:
      class_path: src.envs.wrappers.non_stationary.NonStationaryWrapper
      init_args:
        change_after_timestep: 100
    env:
      class_path: src.envs.toy_goal_env.ToyGoal1DEnv
      init_args:
        goal_sampler: src.envs.samplers.random_box_sampler.RandomBoxSampler
  eval_env:
    n_envs: 36
    time_limit: 200
    vec_env: stable_baselines3.common.vec_env.DummyVecEnv
    cemrl_wrapper: src.cemrl.wrappers.CEMRLWrapper
    heatmap: src.envs.wrappers.heatmap.HeatmapWrapper
    success: src.envs.wrappers.success.PercentageSuccessWrapper
    non_stationary:
      class_path: src.envs.wrappers.non_stationary.NonStationaryWrapper
      init_args:
        change_after_timestep: 100
    env:
      class_path: src.envs.toy_goal_env.ToyGoal1DEnv
      init_args:
        goal_sampler: src.envs.samplers.UniformCircleSampler
  exploration_env: ${envs.env}
  exploration_eval_env: ${envs.eval_env}