envs:
  env:
    env:
      init_args:
        random_position: True
  eval_env:
    env:
      init_args:
        random_position: True
  exploration_env: ${envs.env}
  exploration_eval_env: ${envs.eval_env}