main:
  algorithm:
    init_args:
      tensorboard_log: "logs/toy-goal-1d/cemrl/random_start"
envs:
  env:
    env:
      init_args:
        random_position: True
  eval_env:
    env:
      init_args:
        random_position: True
  exploration_env: ${envs.env}
  exploration_eval_env: ${envs.eval_env}